services:
  editor:
    build:
      context: ./editor
      dockerfile: Dockerfile
    container_name: "gpx-editor"
    ports:
      - 80:80
    networks:
      - default
    restart: unless-stopped

networks:
  default:
    driver: bridge